on:
  push:
  pull_request:

name: 🧪 Test

jobs:
  test-addon:
    runs-on: ubuntu-latest
    container: archlinux:base-devel

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v3

      - name: 👷 Build Dependencies
        run: "pacman --noconfirm -Syu base-devel cmake gcc git make pipewire pipewire-pulse"

      - name: 🍃 Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: 🍃 Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: 🔨 Build
        run: "pnpm install"

      - name: 🧪 Test
        run: "pnpm run test"
